// <auto-generated />
namespace CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class nameguncellmesioldu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nameguncellmesioldu));
        
        string IMigrationMetadata.Id
        {
            get { return "201909241313131_nameguncellmesioldu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
